version = 0.1
[default.deploy.parameters]
stack_name = "phostack-sam"
resolve_s3 = true
s3_prefix = "phostack-sam"
region = "us-east-1"
profile = "cpsc4911"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
